SET foreign_key_checks = 0;
DROP TABLE IF EXISTS `#__bookpro_country`;
DROP TABLE IF EXISTS `#__bookpro_cgroup`;
DROP TABLE IF EXISTS `#__bookpro_busstop`;
DROP TABLE IF EXISTS `#__bookpro_bustrip`;
DROP TABLE IF EXISTS `#__bookpro_bus`;
DROP TABLE IF EXISTS `#__bookpro_passenger`;
DROP TABLE IF EXISTS `#__bookpro_application`;
DROP TABLE IF EXISTS `#__bookpro_orders`;
DROP TABLE IF EXISTS `#__bookpro_region`;
DROP TABLE IF EXISTS `#__bookpro_state`;
DROP TABLE IF EXISTS `#__bookpro_bus_seattemplate`;
DROP TABLE IF EXISTS `#__bookpro_roomratelog`;
DROP TABLE IF EXISTS `#__bookpro_roomrate`;
DROP TABLE IF EXISTS `#__bookpro_agent`;
DROP TABLE IF EXISTS `#__bookpro_dest`;
DROP TABLE IF EXISTS `#__bookpro_customer`;
DROP TABLE IF EXISTS `#__bookpro_job`;
SET foreign_key_checks = 1;